### ISSUE TITLE
Source of API enpoints

### ISSUE THREAD

**Issue by RobJohnston** [PaitoAnderson/coinsquare-csharp#1]
Hello @PaitoAnderson,

I'm wondering what your source is for some of the endpoints.  I've only found documentation for the ticker and order book from here:  https://classic.coinsquare.io/?method=img&tag=RESZFAQ.  But from where did you get `/auth/account/balances` and `/auth/orders/quicktrade` and such?

**Comment by PaitoAnderson** [comment]
It's just based on what I see in the Chrome DevTools Network tab when using their website.

**Comment by RobJohnston** [comment]
Ah, I see.  Thanks.
